### ISSUE TITLE
Does not work as intended on Windows

### ISSUE THREAD

**Issue by haakonmt** [kiliman/remix-flat-routes#10]
`remix routes` returns a different (and erronous) result when run on Windows vs. a unix-based environment.

It looks like a simple path separator issue, where the library assumes `/`, but Windows uses `\`. Can most likely be mitigated by using `path.sep` in the right places instead.

**Comment by kiliman** [comment]
Thanks for the bug report. I'm in the process of rewriting the route parser. I will make sure to update it to account for differences in path separators.
