### ISSUE TITLE
routes with + in a S3 bucket are causing issues with Remix trying to resolve these chunks

### ISSUE THREAD

**Issue by alexhoo** [kiliman/remix-flat-routes#113]
Im trying to upload static assets from Remix to a S3 Bucket from Aws (public/build). The problem is that S3 is not friend of characters like + in the url. Since most of my Remix paths contains this + character, is there any way to deal with this situation?
Im using Remix + Express layer.

![Screenshot 2024-03-26 at 16 49 23](https://github.com/kiliman/remix-flat-routes/assets/1938383/1a3b668f-a376-45f8-ae50-cae39f243cb9)

**Comment by kiliman** [comment]
Interesting. I guess I can understand since, technically, a `+` in the URL is translated to a `space.`

Try adding this to your `remix.config.js`

```ts
  routes: async defineRoutes => {
    const routes = flatRoutes('routes', defineRoutes)
    // remove + in route ids
    const newRoutes = {}
    Object.entries(routes).forEach(([routeId, route]) => {
      route.id = routeId.replaceAll('+', '')
      if (route.parentId) {
        route.parentId = route.parentId.replaceAll('+', '')
      }
      newRoutes[route.id] = route
    })
    return newRoutes
  },
```

NOTE: If you use any route IDs in your app, you must update them to remove the `+`.

**Comment by alexhoo** [comment]
Thank you @kiliman for your quick answer! It worked just fine!

**Comment by kiliman** [comment]
Awesome!
