### ISSUE TITLE
npx migrate doesnt work with Vite bundled Remix apps

### ISSUE THREAD

**Issue by shmuli9** [kiliman/remix-flat-routes#121]
In Vite builds, there is no remix.config, instead all remix configs are in the vite.config file

> npx migrate-flat-routes app/routes app/routes2
> node:internal/modules/cjs/loader:1146
>   throw err;
>   ^
> 
> Error: Cannot find module 'C:\Users\xxx\Coding\app\remix.config.js'
> Require stack:
> - C:\Users\xxx\Coding\app\node_modules\remix-flat-routes\dist\migrate.js
> - C:\Users\xxx\Coding\app\node_modules\remix-flat-routes\dist\cli.js
>     at Module._resolveFilename (node:internal/modules/cjs/loader:1143:15)
>     at Module._load (node:internal/modules/cjs/loader:984:27)
>     at Module.require (node:internal/modules/cjs/loader:1231:19)
>     at require (node:internal/modules/helpers:179:18)
>     at migrate (C:\Users\xxx\Coding\app\node_modules\remix-flat-routes\dist\migrate.js:46:29)
>     at main (C:\Users\xxx\Coding\app\node_modules\remix-flat-routes\dist\cli.js:78:27)
>     at Object.<anonymous> (C:\Users\xxx\Coding\app\node_modules\remix-flat-routes\dist\cli.js:30:1)
>     at Module._compile (node:internal/modules/cjs/loader:1369:14)
>     at Module._extensions..js (node:internal/modules/cjs/loader:1427:10)
>     at Module.load (node:internal/modules/cjs/loader:1206:32) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [
>     'C:\\Users\\xxx\\Coding\\app\\node_modules\\remix-flat-routes\\dist\\migrate.js',
>     'C:\\Users\\xxx\\Coding\\app\\node_modules\\remix-flat-routes\\dist\\cli.js'
>   ]
> }

**Comment by kiliman** [comment]
Fixed in v0.6.5
