### ISSUE TITLE
How to define a route if extension of the file is variable?

### ISSUE THREAD

**Issue by lilouartz** [kiliman/remix-flat-routes#129]
Both of these should be valid URLs:

* https://pillser.com/supplements/100-pure-krill-oil-3336/images/supplement-facts.webp
* https://pillser.com/supplements/100-pure-krill-oil-3336/images/supplement-facts.avif

I tried:

```
supplement-facts.$format/_route.tsx
supplement-facts[.]$format/_route.tsx
supplement-facts[.$format]/_route.tsx
```

None of the above work.

**Comment by lilouartz** [comment]
Not a clue. Tried everything. Would be really handy to have this in the documentation.

**Comment by kiliman** [comment]
Unfortunately, a dynamic param `$format` must be the _entire_ URL segment, not just a part of it. This is a limitation of React Router.

So if you need to be able to handle any type of file extension, you'll need to do something like this:
```ts
// routes/supplements.$product.images.$filename
export async function loader({ params }: LoaderFunctionArgs) {
  const { filename } = params
  if (!/^supplement-facts\.(webp|avif)$/.test(filename)) {
    throw new Response('Not Found', { status: 404 })
  }
  // return image file as a response
}
```

**Comment by lilouartz** [comment]
ah this explains it! maybe worth adding a callout to the docs because I've spent like two hours experimenting with this haha

**Comment by lilouartz** [comment]
Thank you for the response
