### ISSUE TITLE
How to override default param prefix?

### ISSUE THREAD

**Issue by lilouartz** [kiliman/remix-flat-routes#135]
Documentation says it is possible:

> You can override the default param prefix of $. Some shells use the $ prefix for variables, and this can be an issue due to shell expansion. Use any character that is a valid filename, for example: ^

https://github.com/kiliman/remix-flat-routes?tab=readme-ov-file#custom-param-prefix

But it does not say how to do it.

**Comment by lilouartz** [comment]
Turns out it is `paramPrefixChar` setting. Documentation is just a bit disconnected.

**Comment by lilouartz** [comment]
Any thoughts on `^` vs `+`?

**Comment by lilouartz** [comment]
Looks like `^` equally causes issues with zsh.

**Comment by lilouartz** [comment]
So it is down to `:` vs `+`.

**Comment by lilouartz** [comment]
`:` has other issues, e.g. cannot easily find files with `:` prefix in VSCode. iTerm fails to open them.

**Comment by lilouartz** [comment]
Looks like `+` is reserved for other use cases, so it is not an option.

Trying `~`.

**Comment by lilouartz** [comment]
`~` works fine in every test scenario I could think of!

I would update documentation to recommend that instead of `+`, which appears to not work with zsh.

**Comment by kiliman** [comment]
Thanks for doing the research. I'll gladly accept a PR if you want to update the README.
