### ISSUE TITLE
Form submitting to incorrect routes

### ISSUE THREAD

**Issue by nakleiderer** [kiliman/remix-flat-routes#14]
After migrating to this library, my forms are submitting to incorrect routes. 

Here's a repro (the README has a lot more detail): https://stackblitz.com/edit/node-kh9dmu?file=README.md

**Comment by puchesjr** [comment]
We have an issue, but it is related to a `userFetcher.Form` in our layout route. The `useFetcher.Form` is in our `search.tsx` sidebar but calls the `Action` on the `search._index.tsx` perhaps we need to declare which `Action` the `useFetcher` should call?

**Comment by kiliman** [comment]
I recommend being explicit with your `action`. And remember, if you're posting to an *index* route, you should always append `?index` to the path.

**Comment by shadyendless** [comment]
> After migrating to this library, my forms are submitting to incorrect routes.
> 
> Here's a repro (the README has a lot more detail): https://stackblitz.com/edit/node-kh9dmu?file=README.md

Looking at your Stackblitz, it looks as though the actions are being invoked properly. I think I may be misunderstanding the issue. Could you explain in more detail how each action is supposed to function?

I've attached a video of the behavior I am seeing.

https://user-images.githubusercontent.com/1154812/199886355-97e0266f-4b2f-47d9-bd53-28e3f735fe48.mp4

**Comment by kentcdodds** [comment]
I'm also experiencing this issue, except with a `<Form>` rather than a `fetcher` or `submit`.

One thing I noticed is that when running `npx remix routes` with flat routes, all the routes are prefixed with `/` whereas with the default all routes do *not* have a `/` prefix. I tried updating things manually in node_modules and removing that prefix didn't affect the outcome so probably not related.

I'll put together a reproduction for you.

**Comment by kentcdodds** [comment]
- Here's what it should do: https://stackblitz.com/edit/node-r3c4zp
- Here's what it does: https://stackblitz.com/edit/node-4rvghn

NOTE: I noticed that StackBlitz isn't completely reliable in running things correctly so I suggest downloading and running locally.

Also one thing I noticed is the form that's actually rendered differs in the two examples. In the one that works, it includes `?index` at the end of the action attribute, and the flat routes one does not.

**Comment by kiliman** [comment]
Interesting. Thanks for the repro. I'm finishing up my Remix Conf presentation, but I will get to this ASAP.

**Comment by kiliman** [comment]
Thanks for the research. I was surprised when this started breaking, as I haven't had any issues in my app which has over 100 routes, but I also haven't updated to the latest yet either. Anyway, I will get to the bottom of this. Remix flat routes should generate the same routing structure as the conventional routes.

**Comment by kiliman** [comment]
I found the problems. First is a bug in my route generation, but the other is a bug in Remix in how it matches the index route. It was checking if the URL ends in `/index` (which won't be true for flat routes), when it should be looking at `route.index === true` since that's already defined in the route config.

Here's the patch for Remix. I'll be updating the flat routes package.

```diff
diff --git a/node_modules/@remix-run/server-runtime/dist/server.js b/node_modules/@remix-run/server-runtime/dist/server.js
index 5ac2304..58e39f3 100644
--- a/node_modules/@remix-run/server-runtime/dist/server.js
+++ b/node_modules/@remix-run/server-runtime/dist/server.js
@@ -503,7 +503,7 @@ function isIndexRequestUrl(url) {
 function getRequestMatch(url, matches) {
   let match = matches.slice(-1)[0];
 
-  if (isIndexRequestUrl(url) && match.route.id.endsWith("/index")) {
+  if (isIndexRequestUrl(url) && match.route.index) {
     return match;
   }
```

**Comment by kiliman** [comment]
One other Remix patch. This time it's to fix the index handling for the Form action. Again Remix is checking for ending in `/index`, when it should be getting the `index` prop from the routes config (available from entry context manifest)

```diff
diff --git a/node_modules/@remix-run/react/dist/esm/components.js b/node_modules/@remix-run/react/dist/esm/components.js
index e884e7b..56ddff4 100644
--- a/node_modules/@remix-run/react/dist/esm/components.js
+++ b/node_modules/@remix-run/react/dist/esm/components.js
@@ -746,6 +746,7 @@ FormImpl.displayName = "FormImpl";
  */
 function useFormAction(action, // TODO: Remove method param in v2 as it's no longer needed and is a breaking change
 method = "get") {
+  let { manifest }= useRemixEntryContext()
   let {
     id
   } = useRemixRouteContext();
@@ -760,7 +761,7 @@ method = "get") {
     search,
     hash
   } = resolvedPath;
-  let isIndexRoute = id.endsWith("/index");
+  let isIndexRoute = manifest.routes[id].index
 
   if (action == null) {
     search = location.search;
```

**Comment by kentcdodds** [comment]
Thank you!

**Comment by kiliman** [comment]
While the PR is being reviewd, I'm going to update flat routes to add the `/index` suffix that Remix is currently looking for.

**Comment by kiliman** [comment]
@nakleiderer @lukebowerman @puchesjr @shadyendless 

Please try latest v0.4.8. I added a workaround in the package itself until the PR bug fix has been merged into Remix.

Thanks everyone for your patience.
