### ISSUE TITLE
Conflicts with route when trying to nest routes

### ISSUE THREAD

**Issue by shortnd** [kiliman/remix-flat-routes#20]
When trying to nest a round under a parent route it is returning an error: 

Error: Path "app/calendar" defined by route "routes/app.calendar/index" conflicts with route "routes/app.calendar.index/index"

version: 0.4.4

**Comment by kiliman** [comment]
It's working for me. Do you have a simple repro?
```
❯ tree app/routes-test/
app/routes-test/
├── app.calendar
│   └── index.tsx
└── app.calendar.index
    └── index.tsx
```
```ts
❯ npx remix routes
<Routes>
  <Route file="root.tsx">
    <Route path="app/calendar" file="routes-test/app.calendar/index.tsx">
      <Route index file="routes-test/app.calendar.index/index.tsx" />
    </Route>
  </Route>
</Routes>
```
```ts
// routes/app.calendar/index.tsx
import { Outlet } from '@remix-run/react'

export default function CalendarLayout() {
  return (
    <div>
      <h1>Calendar Layout</h1>
      <Outlet />
    </div>
  )
}

// routes/app.calendar.index/index.tsx
export default function CalendarIndex() {
  return (
    <div>
      <h2>Calendar Index</h2>
    </div>
  )
}
```
<img width="441" alt="image" src="https://user-images.githubusercontent.com/47168/199567336-b22c4b16-8445-4382-b599-b4b805586955.png">

**Comment by shortnd** [comment]
Here is a link to the test project I created. I tried it again and still seem to be having the issue..

https://github.com/shortnd/make-it-flat

Exact error message is:
Error: Path "app/calendar" defined by route "routes/app.calendar/index" conflicts with route "routes/app.calendar.index/index"

**Comment by kiliman** [comment]
The issue is in your *remix.config*.

Since Remix still tries to process your *routes* folder with the default config, you need to tell Remix to ignore *everything* in the folder. Your config is only ignore files with leading dot `.`. Change to `"**/*"` and it'll work.

This should be much easier once flat routes becomes a core part of Remix.

```js
module.exports = {
  ignoredRouteFiles: ["**/*"],
  // appDirectory: "app",
  // assetsBuildDirectory: "public/build",
  // serverBuildPath: "build/index.js",
  // publicPath: "/build/",
  routes: async defineRoutes => flatRoutes('routes', defineRoutes),
}
```
