### ISSUE TITLE
Flat Route Convention route matching problem

### ISSUE THREAD

**Issue by stephen776** [kiliman/remix-flat-routes#24]
I am having an issue with the flat directories convention.  This appears to be a bug unless I'm misunderstanding the convention.

I have the following structure

```
routes/
  _dashbaord/
    _index.tsx <- pathless layout route

  _dashboard.foo.index/
    _index.tsx <- index route nested in dashboard layout

  _dashboard.foo.$id/
    _index.tsx <-detail page under dashboard layout - this renders an Outlet

  _dashboard.foo.$id.delete/
    _index.tsx <- renders as a child of the above route (a delete confirmation modal)

  _dashboard.foo_.create/
    _index.tsx <- renders as a child of LAYOUT - does not next under the above Outlet

  _dashboard.foo_.$id.edit/
    _index.tsx <- SHOULD renders as a child of LAYOUT (this breaks)

```

What I am noticing is that the last route above (edit) matches on both of the following:

`_dashboard.foo.$id/`
` _dashboard.foo_.$id.edit/`

Where I do not want to match on the 1st "details" route. I want "edit" to be nested inside LAYOUT. In this current scenario only the "details" route is actually rendered (so I'm not even getting the page I want) but loaders for both are being called.

**Comment by stephen776** [comment]
I'm putting together a repo to reproduce

**Comment by kiliman** [comment]
Thanks. I'll take a look. What does `npx remix routes` show?
