### ISSUE TITLE
Does not respect configured appDirectory

### ISSUE THREAD

**Issue by rogerchi** [kiliman/remix-flat-routes#26]
It seems like the `appDirectory` is hard-coded to `app`, so if you've changed it (for me it's set to `remix/app`), you get an error.  Would be ideal if remix-flat-routes respected the `appDirectory` parameter.

https://github.com/kiliman/remix-flat-routes/blob/1456a5b88b8e91c6288e0c50aeb5a508c1c72303/src/index.ts#L72

**Comment by kiliman** [comment]
Thanks. I'll add it to the options.

**Comment by antoinechalifour** [comment]
Thanks for your work @kiliman ! Can't wait to use this plugin once the option is shipped 👍

**Comment by kiliman** [comment]
Fixed in v0.5.2
