### ISSUE TITLE
Flat files folders, support for windows

### ISSUE THREAD

**Issue by t19n** [kiliman/remix-flat-routes#27]
Hi,
found out that the nested folders with flat files does not work on windows.
example:
```
└── users+
    ├─ $userId.tsx
```

on linux you would get auth+/$userId.tsx but on windows you get auth+\\$userId.tsx,
seems to be that routeRegex in defaultOptions is not correct, at least does not support win backslashes .

Regards, Thorsteinn

**Comment by kiliman** [comment]
Thanks for the bug report. I'll get that fixed!

**Comment by kiliman** [comment]
Fixed in v0.5.2
