### ISSUE TITLE
Flat Routes - Route Segment after Param

### ISSUE THREAD

**Issue by 58bits** [kiliman/remix-flat-routes#31]
Hi Michael,

remix-flat-routes looks great. 

I was trying to implement flat-routes on our current 'workbench' Remix app - starting with 'flat-files', before trying 'flat-folders' or 'nested' or 'hybrid'.

For the following 'flat-files' route files....

```
.
├── _auth.sign-in.tsx
├── _auth.sign-out.tsx
├── _auth.sign-up.tsx
├── _auth.tsx
├── actions.set-theme.tsx
├── app.notes.$noteId.delete.tsx
├── app.notes.$noteId.edit.tsx
├── app.notes.$noteId.tsx
├── app.notes.index.tsx
├── app.notes.new.tsx
├── app.tsx
├── healthcheck.tsx
├── index.css
└── index.tsx
```

Should the `app.notes.$noteId.edit.tsx` and `app.notes.$notedId.delete.tsx` routes work?

The server routes for  `/app/notes/<note-id>/edit`  `/app/notes/<note-id>/delete` seem to be working  (the correct loader is being called), but in the browser, the `edit` and `delete` routes are re-rendering the `/app/notes/<note-id>` route and not the `edit` or `delete` React page components.

Are we doing something wrong?

**Comment by 58bits** [comment]
I've just tried to reproduce this on a clean Indie Stack install and I'm pretty sure I'm seeing the same problem here. The server received the route, loader runs, but the browser router stays on the note details page - double rendering the components...

I've setup a test repo here - https://github.com/infonomic/flat-routes-test  -  again, based on a clean Indie stack install with the following routes.

```
.
├── _auth.join.tsx
├── _auth.login.tsx
├── _auth.logout.tsx
├── app.notes.$noteId.edit.tsx
├── app.notes.$noteId.tsx
├── app.notes.index.tsx
├── app.notes.new.tsx
├── app.notes.tsx
├── healthcheck.tsx
└── index.tsx
```
Hope some of this helps, and apologies in advance if I've somehow mixed things up.

**Comment by kiliman** [comment]
Can you run `npx remix routes` and paste the output? Thanks

**Comment by kiliman** [comment]
Does `$noteId` have an `<Outlet>`?

**Comment by 58bits** [comment]
Sure - here's the results of `npm remix routes` from the test repo....

```
<Routes>
  <Route file="root.tsx">
    <Route path="join" file="routes/_auth.join.tsx" />
    <Route path="login" file="routes/_auth.login.tsx" />
    <Route path="logout" file="routes/_auth.logout.tsx" />
    <Route path="app/notes" file="routes/app.notes.tsx">
      <Route path=":noteId" file="routes/app.notes.$noteId.tsx">
        <Route path="edit" file="routes/app.notes.$noteId.edit.tsx" />
      </Route>
      <Route path="new" file="routes/app.notes.new.tsx" />
      <Route index file="routes/app.notes.index.tsx" />
    </Route>
    <Route path="healthcheck" file="routes/healthcheck.tsx" />
    <Route index file="routes/index.tsx" />
  </Route>
</Routes>
```

And no - neither `app.notes.$noteId.tsx` nor `app.notes.$noteId.edit.tsx` has an outlet (only `app.notes.tsx` does)

**Comment by kiliman** [comment]
Ok that's what I thought. By default it is looking for the matching parent route. 

Since `$noteId` matches on your new and edit routes, it thinks that's the parent. 

Rename your routes to add the `_` suffix to say it doesn't have an `outlet`. Then it will match the _notes_ route

`notes.$noteId_.new.tsx`

**Comment by 58bits** [comment]
Okay that worked.

```
<Routes>
  <Route file="root.tsx">
    <Route path="join" file="routes/_auth.join.tsx" />
    <Route path="login" file="routes/_auth.login.tsx" />
    <Route path="logout" file="routes/_auth.logout.tsx" />
    <Route path="app/notes" file="routes/app.notes.tsx">
      <Route path=":noteId" file="routes/app.notes.$noteId.tsx" />
      <Route path=":noteId/edit" file="routes/app.notes.$noteId_.edit.tsx" />
      <Route path="new" file="routes/app.notes.new.tsx" />
      <Route index file="routes/app.notes.index.tsx" />
    </Route>
    <Route path="healthcheck" file="routes/healthcheck.tsx" />
    <Route index file="routes/index.tsx" />
  </Route>
</Routes>
```

**Comment by 58bits** [comment]
I do recall reading about the '_' suffix and it's behavior, but did put it together for this case. I'll go back and take a look at the docs again, and if you think some extra text or an example would help I'd be glad to submit a PR.

**Comment by kiliman** [comment]
Yeah I need to write more documentation. I plan on doing some videos showing the different conventions as well.

**Comment by 58bits** [comment]
Okay - we'll I'd be glad to lend a hand with the docs if I can be of help. Will close this issue if that's okay with you.

**Comment by 58bits** [comment]
This is sweet. You guys are on another level ;-)

```
.
├── _actions+
│   └── actions.set-theme.tsx
├── _app+
│   ├── _app.tsx
│   ├── account.$userId.email.tsx
│   ├── account.$userId.password.tsx
│   ├── account.index.tsx
│   ├── notes.$noteId.tsx
│   ├── notes.$noteId_.delete.tsx
│   ├── notes.$noteId_.edit.tsx
│   ├── notes.index.tsx
│   └── notes.new.tsx
├── _auth+
│   ├── _auth.tsx
│   ├── sign-in.tsx
│   ├── sign-out.tsx
│   └── sign-up.tsx
├── _landing+
│   ├── _landing.tsx
│   ├── index.css
│   └── index.tsx
├── admin+
│   ├── _admin.tsx
│   ├── index.tsx
│   ├── users.tsx
│   └── users_.$userId.tsx
├── healthcheck.tsx
├── theme-radix-dialog.tsx
├── theme-radix-toast.tsx
├── theme-tailwind-forms.tsx
└── theme.tsx
```

**Comment by kiliman** [comment]
Yeah, I really like the new `+` convention. It allows you to organize the routes and shorten the names.
