### ISSUE TITLE
V1 Nested Layout Routes Fail to function with flat-routing enabled

### ISSUE THREAD

**Issue by bengavin** [kiliman/remix-flat-routes#51]
I have the following working layout in v 1.15 (v1 routing)

- routes
  - bookmarks
    - __leftnav
      - $bookmarkId.edit.tsx
      - $bookmarkId.tsx
      - new.tsx
    - __leftnav.tsx <-- layout
    - index.tsx
  - bookmarks.tsx <-- layout
  - index.tsx

It seems, no matter what I do, I am unable to convince vanilla v2 routing, nor remix-flat-routes to render this particular route hierarchy.  It always seems to end with some variant of the routes conflicting, or the layout files (and associated loader methods) not being executed properly.  The closest I've gotten by disabling the uniqueness check allows most everything other than the '$bookmarkId.edit.tsx' route to function correctly.

How should the above hierarchy be managed in Remix w/ remix-flat-routes?  Conceptually, the 'LeftNav' layout should be nested within the 'Bookmarks' layout when on the 'Edit/View/New' page.

Thanks!

**Comment by kiliman** [comment]
I think there's a bug in the `v2` uniqueness check. `remix-flat-routes` copies the logic from `v2`, but I did add a flag to disable that, since I believe it is not correct most of the time. Especially when you have pathless layouts or optional route segments.

```js
module.exports = {
  ignoredRouteFiles: ["**/*"],
  routes: async (defineRoutes) => {
    return flatRoutes("routes", defineRoutes, { enableUniqueIdCheck: false });
  },
}
```
```
app/routes
├── _index.tsx
├── bookmarks._index.tsx
├── bookmarks._leftnav.$bookmarkId.tsx
├── bookmarks._leftnav.$bookmarkId_.edit.tsx
├── bookmarks._leftnav.new.tsx
├── bookmarks._leftnav.tsx
└── bookmarks.tsx
```
```ts
<Routes>
  <Route file="root.tsx">
    <Route path="bookmarks" file="routes/bookmarks.tsx">
      <Route file="routes/bookmarks._leftnav.tsx">
        <Route path=":bookmarkId" file="routes/bookmarks._leftnav.$bookmarkId.tsx" />
        <Route path=":bookmarkId/edit" file="routes/bookmarks._leftnav.$bookmarkId_.edit.tsx" />
        <Route path="new" file="routes/bookmarks._leftnav.new.tsx" />
      </Route>
      <Route index file="routes/bookmarks._index.tsx" />
    </Route>
    <Route index file="routes/_index.tsx" />
  </Route>
</Routes>
```

**Comment by kiliman** [comment]
NOTE: You'll see that for the edit route, I added the trailing `_` to `$bookmarkId_`. This ensures that `edit` is nested under `_leftnav` and *not* `$bookmarkId`
