### ISSUE TITLE
New routes not detected on Windows

### ISSUE THREAD

**Issue by xHomu** [kiliman/remix-flat-routes#59]
Noticed this with Epic Stack and was able to nail down the issue as remix-flat-routes. Weird that no one caught this before:

### What version of Remix are you using?

v1.18.1

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

(As a sanity check, I was able to confirm that this is unrelated to v2_dev server.)

1. On a Windows environment, clone the bug repo https://github.com/xHomu/remix-v2-server/tree/flat-route-bug
2. `npm install; npm run dev` 
3. Create `app/routes/test.tsx` and a basic export default component.
4. Visit `localhost:3000/test`

### Expected Behavior

See the test route.

### Actual Behavior

404 Not Found thrown.

![image](https://github.com/kiliman/remix-flat-routes/assets/84349818/bdb88ded-5b53-4de3-bcf8-c00f78fe02ea)

* If we restart the dev server manually, `localhost:3000/test` renders correctly.
* Edits to existing route files work as expected.
* If we comment out flat routes in remix.config and repeat steps 1-4, `localhost:3000/test` renders correctly without error.

---

Possible related issue from remix core: https://github.com/remix-run/remix/pull/6293/files

**Comment by kiliman** [comment]
Ok, there are a couple of things.

1. It appears that Remix wants the filename normalized to `/` separators, even on Windows. I normalize the route `id`, but keep the filename as the original path. I'll update that.
2. In your *remix.config*, you need to make sure you to update `ignoredRoutesFiles` to `['**/*']` (ignore *all* files). Otherwise, the `v2` convention will pick them up. You can still ignore files by passing them in options to the `flatRoutes()` function.

**Comment by xHomu** [comment]
Ops, fixed #2. Any idea why this only occurs during dev and not if we manually restart?

**Comment by kiliman** [comment]
I just updated my workaround with a fix. I have a feeling the new dev server expects `/` paths only to determine if it was a route file that changed.

**Comment by kiliman** [comment]
Let me know if that fixes the issue, and I'll be sure to include that in the next update.

**Comment by xHomu** [comment]
Before I forgot, Happy Independence Day!

**Comment by kiliman** [comment]
Thanks. Yeah, I've got a couple of other changes then I'll push out the fix.

**Comment by xHomu** [comment]
Will the next package be released pretty quickly, or we should go ahead and implement the workaround for now for the Epic Stack?

**Comment by kiliman** [comment]
Ok, I pushed out v0.5.9 which includes the fix.

**Comment by xHomu** [comment]
Can confirm v0.5.9 fixed the bug. Thanks again, @kiliman!
