### ISSUE TITLE
Unable to dialog routes to work

### ISSUE THREAD

**Issue by varndellwagglebee** [kiliman/remix-flat-routes#76]
We have several dialog boxes that we want to have routes.  

Example:  _private+
                     library/
                       glyphs/
                             _list
                             new.tsx - this is our modal.

THank you in advanced.

**Comment by kiliman** [comment]
I'm not clear on the file structure. Can you run `tree app/routes` and paste the result inside a fenced block (3 backticks).

Also can you run `npx remix routes` to see how Remix configured your routes?

Thanks!

**Comment by varndellwagglebee** [comment]
We have printed out the routes and we can’t seem to get the dialog modal in a route.

 

We have a list of items.  When you click on the name, we want a dialog box to appear with its own route.  We’ve tried several different scenarios.

 

'routes/_private+/library/_layout': {

    path: 'library',

    index: undefined,

    caseSensitive: undefined,

    id: 'routes/_private+/library/_layout',

    parentId: 'routes/_private+/_private',

    file: 'routes/_private+/library/_layout.tsx'

  },

  'routes/_private+/library/glyphs/index': {

    path: 'glyphs',

    index: undefined,

    caseSensitive: undefined,

    id: 'routes/_private+/library/glyphs/index',

    parentId: 'routes/_private+/library/_layout',

    file: 'routes/_private+/library/glyphs/index.tsx'

  },

  'routes/_private+/library/glyphs/list/_list': {

    path: 'list',

    index: undefined,

    caseSensitive: undefined,

    id: 'routes/_private+/library/glyphs/list/_list',

    parentId: 'routes/_private+/library/glyphs/index',

    file: 'routes/_private+/library/glyphs/list/_list.tsx'

  },

  'routes/_private+/library/glyphs/list/­new': {

    path: 'list',     <<<<<<<<<<<<<<<<HERE

    index: undefined,

    caseSensitive: undefined,

    id: 'routes/_private+/library/glyphs/list/_new',

    parentId: 'routes/_private+/library/glyphs/index',

    file: 'routes/_private+/library/glyphs/list/_new.tsx'

  },

 

 

Annette Findley

 

Email:  ***@***.***> ***@***.***

 

6531 Britannic Place

Frederick, MD  21703

**Comment by kiliman** [comment]
Your issue is that `remix-flat-routes` treats the contents of `glyphs/list/*` as collocated files for the `list` route. When the final folder is a regular folder (not one ending with `+`), it will assume the contents are collocated.


So `_list.tsx` is the route module for the `list` route (because it starts with `_`). When it sees `_new.tsx`, it also thinks it's the module for the `list` route. That's why you get the same `path` attribute.

When you're inside a collocated folder, you can explicitly specify a file as being a new route module by adding the `.route` suffix: `new.route.tsx`.

```bash
❯ tree app/routes
app/routes
└── _private+
    └── library
        ├── _layout.tsx
        └── glyphs
            ├── index.tsx
            └── list
                ├── _list.tsx
                └── new.route.tsx
```
```xml
❯ npx remix routes
<Routes>
  <Route file="root.tsx">
    <Route path="library" file="routes-76/_private+/library/_layout.tsx">
      <Route path="glyphs" file="routes-76/_private+/library/glyphs/index.tsx">
        <Route path="list" file="routes-76/_private+/library/glyphs/list/_list.tsx">
          <Route path="new" file="routes-76/_private+/library/glyphs/list/new.route.tsx" />
        </Route>
      </Route>
    </Route>
  </Route>
</Routes>
```

**Comment by varndellwagglebee** [comment]
How would you do something like this path (_private+/data/$assetid/details/preview)?

 

I tried folder structure

 

_private+/

   Data/

      $assetId/

           Details/

              Preview.route.tsx

 

routes/_private+/data/$assetId/details/preview.route': {

    path: ':assetId/details/preview',

  }

 

 

Annette Findley

Email:  ***@***.***> ***@***.***

 

6531 Britannic Place

Frederick, MD  21703

**Comment by kiliman** [comment]
No offense, but your email responses are kind of hard to read because of the lack of formatting.

Anyway, I'm not sure what the question is. Based on your route, the path looks fine. It looks like it is nested under the `data` route.

Please run `npx remix routes` to see the route structure. It should look like the example in my previous response.

**Comment by varndellwagglebee** [comment]
Sorry about that.  I figured what I need.  

 

I have another question.  I have a route’s file that has a redirect.  However, the redirect isn’t getting hit.    What we want to have happen, if I go to data/1/details  route, it will redirect to data/1/details/settings

 

 



 

 

Annette Findley

 

Email:  ***@***.***> ***@***.***

 

6531 Britannic Place

Frederick, MD  21703

**Comment by varndellwagglebee** [comment]
Hello Kiliman,

 

I wanted to let you know that I figured out the issue.  I needed the “_”

 

Thank you again for your assistance.

 

Annette Findley

 

Email:  ***@***.***> ***@***.***

 

6531 Britannic Place

Frederick, MD  21703
