### ISSUE TITLE
Unclear docs about integration with Remix Core 

### ISSUE THREAD

**Issue by cjoecker** [kiliman/remix-flat-routes#92]
[In the docs](https://github.com/kiliman/remix-flat-routes/blob/main/README.md?plain=1#L13-L17), It says the `remix-flat-routes` will be integrated to remix core.

For me, the following is not clear:
1. What features of `remix-flat-routes` will be integrated in Remix Core
2. What features will stay only in `remix-flat-routes` in the near feature
3. When will `remix-flat-routes` be integrated in Remix Core (if it is not already integrated)

**Comment by kiliman** [comment]
I suppose I need to update that part of the README.

`remix-flat-routes` was the initial implementation of the flat routes spec. I added some enhancements to it based on user feedback.

When Ryan decided to make flat routes the default convention, he opted to only use the original spec. This is what is now the `v2` routing convention.

So if you want *hybrid* routes, extended route filenames, etc., you'll still need to use the `remix-flat-routes` package. This package will always maintain compatibility with the Remix convention. It is simply a superset/extension.
