### ISSUE TITLE
Snapshopts in route files breaks migrate-flat-routes

### ISSUE THREAD

**Issue by cjoecker** [kiliman/remix-flat-routes#93]
I have snapshot files in my routes folder like `app/routes/__snapshots__/jobs.connection-check.test.ts.snap`

When I run `migrate-flat-routes`, I get this error:
`Error: Invalid route module file: app/routes/__snapshots__/jobs.connection-check.test.ts.snap`

**Comment by kiliman** [comment]
Interesting. Do you use the `ignoredRoutedFiles` setting in _remix.config_?

I should probably read that in during migration.

**Comment by kiliman** [comment]
This has been fixed in v0.6.4

**Comment by cjoecker** [comment]
@kiliman yeah, I use `ignoredRoutedFiles`. Thanks for fixing it!
