### ISSUE TITLE
How to match all descending paths?

### ISSUE THREAD

**Issue by adaboese** [kiliman/remix-flat-routes#97]
I want to match `/images/$anythingThatFollows`

I tried `/routes/images/$path`, but it matches only the first path segment, i.e. it won't work with /images/foo/bar/baz.jpg

**Comment by kiliman** [comment]
Try `routes/images.$.tsx`

The `$` by itself is a _splat_ route and matches everything, including `/`.

You access it from your loader using `params['*']`

https://remix.run/docs/en/main/file-conventions/routes#splat-routes

**Comment by adaboese** [comment]
That's it. Thank you!
